export default [
  {
    title: 'Total Population',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'number',
    variable: 'pop_1',
    table: 'demographic',
    enabled: false,
  },
  {
    title: 'Population under age 18',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'popu181',
    table: 'demographic',
    enabled: false,
  },
  {
    title: 'Population 65 and over',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'pop65pl1',
    table: 'demographic',
    enabled: false,
  },
  {
    title: 'Median Age',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'number',
    variable: 'mdage',
    table: 'demographic',
    enabled: false,
  },
  {
    title: 'White Non-hispanic',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'wtnh',
    table: 'demographic',
    enabled: false,
  },
  {
    title: 'Black Non-hispanic',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'blnh',
    table: 'demographic',
    enabled: false,
  },
  {
    title: 'Asian Non-hispanic',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'asnnh',
    table: 'demographic',
    enabled: false,
  },
  {
    title: 'Hispanic',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'hsp1',
    table: 'demographic',
    enabled: false,
  },
  {
    title: 'Nonfamily Households',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'nfam1',
    table: 'social',
    enabled: false,
  },
  {
    title: 'Less than High School Graduate',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'ea_lthsgr',
    table: 'social',
    enabled: false,
  },
  {
    title: 'Bachelor\'s degree or higher',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'ea_bchdh',
    table: 'social',
    enabled: false,
  },
  {
    title: 'Lived in a different house 1 year ago',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'dfhs1',
    table: 'social',
    enabled: false,
  },
  {
    title: 'Foreign Born',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'fb1',
    table: 'social',
    enabled: false,
  },
  {
    title: 'Speak language other than English & speak English less than very well',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'lgoenlep1',
    table: 'social',
    enabled: false,
  },
  {
    title: 'Speak Spanish at home & speak English less than "very well"',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'lgsplep2',
    table: 'social',
    enabled: false,
  },
  {
    title: 'Speak Chinese at home & speak English less than "very well"',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'lgchilep2',
    table: 'social',
    enabled: false,
  },
  {
    title: 'Unemployed',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'cvlfuem2',
    table: 'economic',
    enabled: false,
  },
  {
    title: 'Mean travel time to work (minutes)',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'mntrvtm',
    table: 'economic',
    enabled: false,
  },
  {
    title: 'Median household income',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'mdhhinc',
    table: 'economic',
    enabled: false,
  },
  {
    title: 'No health insurance coverage',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'nhins',
    table: 'economic',
    enabled: false,
  },
  {
    title: 'Population below poverty line',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'fambwpv',
    table: 'economic',
    enabled: false,
  },
  {
    title: 'Renter-occupied housing units',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'rochu',
    table: 'housing',
    enabled: false,
  },
  {
    title: '1.01 or more occupants per room',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'ocpr1pl',
    table: 'housing',
    enabled: false,
  },
  {
    title: 'Median gross rent',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'mdgr',
    table: 'housing',
    enabled: false,
  },
  {
    title: 'Gross rent as a percentage of household income, 35.0 percent or more',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'grpi35pl',
    table: 'housing',
    enabled: false,
  },
];
