export default [
  {
    title: 'Total Population',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'number',
    variable: 'pop_1',
    table: 'demographic',
    defaultRange: null,
    range: null,
    data: null,
    enabled: false,
  },
  {
    title: 'Families living below poverty line',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'fambwpv',
    table: 'economic',
    range: [25, 75],
    data: null,
    enabled: false,
  },
  {
    title: 'Population under age 18',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'popu181',
    table: 'demographic',
    range: [25, 75],
    data: null,
    enabled: false,
  },
  {
    title: 'Population 65 and over',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'pop65pl1',
    table: 'demographic',
    range: [0, 100],
    label: 'percentage of the population 65 and over',
    data: null,
    enabled: false,
  },
  {
    title: 'Population renting home',
    tooltip: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    type: 'percentage',
    variable: 'rochu',
    table: 'housing',
    range: [0, 100],
    label: 'percentage of the population that rent their home',
    data: null,
    enabled: false,
  },
];
