module.exports = function() {
  return {
    'free-solid-svg-icons': [
      'arrow-left',
      'arrow-right',
      'arrow-up',
      'arrow-down',
      'building',
      'caret-down',
      'caret-up',
      'download',
      'edit',
      'exclamation-triangle',
      'external-link-alt',
      'file',
      'info-circle',
      'long-arrow-alt-right',
      'map',
      'map-pin',
      'pen',
      'plus',
      'question-circle',
      'search',
      'sliders-h',
      'square',
      'times',
      'user-friends',
    ],
    'free-regular-svg-icons': [
      'arrow-alt-circle-down',
      'check-square',
      'circle',
      'copy',
      'dot-circle',
      'envelope',
      'hand-pointer',
      'object-group',
      'square',
    ],
  };
};
