export default [
  {
    id: 'decennial-2020',
    label: '2020 Decennial Census',
    type: 'census',
    year: '2020',
    changeOverTime: false,
    selected: true,
  },
  {
    id: 'decennial-2010',
    label: '2010 Decennial Census',
    type: 'census',
    year: '2010',
    changeOverTime: false,
    selected: false,
  },
  {
    id: 'decennial-change',
    label: 'Change over Time: Decennial Census 2020, 2010',
    type: 'census',
    year: null,
    changeOverTime: true,
    selected: false,
  },
  {
    id: 'acs-2015-2019',
    label: '2015 - 2019 ACS',
    type: 'acs',
    year: '2015-2019',
    changeOverTime: false,
    selected: false,
  },
  {
    id: 'acs-2006-2010',
    label: '2006 - 2010 ACS',
    type: 'acs',
    year: '2006-2010',
    changeOverTime: false,
    selected: false,
  },
  {
    id: 'acs-change',
    label: 'Change over Time: ACS 2006-2010 to 2015-2019',
    type: 'acs',
    year: null,
    changeOverTime: true,
    selected: false,
  },
];
