export default [
  {
    id: 'decennial-current',
    label: '2020 Decennial Census',
    type: 'census',
    year: '2020',
    mode: 'current',
    selected: true,
  },
  {
    id: 'decennial-previous',
    label: '2010 Decennial Census',
    type: 'census',
    year: '2010',
    mode: 'previous',
    selected: false,
  },
  {
    id: 'decennial-change',
    label: 'Change over Time: Decennial Census 2020, 2010',
    type: 'census',
    year: null,
    mode: 'change',
    selected: false,
  },
  {
    id: 'acs-current',
    label: '2015 - 2019 ACS',
    type: 'acs',
    year: '2015-2019',
    mode: 'current',
    selected: false,
  },
  {
    id: 'acs-previous',
    label: '2006 - 2010 ACS',
    type: 'acs',
    year: '2006-2010',
    mode: 'previous',
    selected: false,
  },
  {
    id: 'acs-change',
    label: 'Change over Time: ACS 2006-2010 to 2015-2019',
    type: 'acs',
    year: null,
    mode: 'change',
    selected: false,
  },
];
