import DS from 'ember-data';

export default DS.Model.extend({
  base: DS.attr('number'),
  base_join: DS.attr('number'),
  base_m: DS.attr('number'),
  base_sum: DS.attr('number'),
  base_year: DS.attr('number'),
  cartodb_id: DS.attr('number'),
  category: DS.attr('string'),
  comparison_base_join: DS.attr('number'),
  comparison_base_m: DS.attr('number'),
  comparison_base_sum: DS.attr('number'),
  comparison_base_year: DS.attr('number'),
  comparison_cv: DS.attr('number'),
  comparison_m: DS.attr('number'),
  comparison_percent: DS.attr('number'),
  comparison_percent_m: DS.attr('number'),
  comparison_sum: DS.attr('number'),
  cv: DS.attr('number'),
  dataset: DS.attr('string'),
  infltnfctr10to16: DS.attr('number'),
  m: DS.attr('number'),
  notinprofile: DS.attr('boolean'),
  percent: DS.attr('number'),
  percent_m: DS.attr('number'),
  percent_significant: DS.attr('boolean'),
  producttype: DS.attr('string'),
  profile: DS.attr('string'),
  release_year: DS.attr('string'),
  significant: DS.attr('boolean'),
  sum: DS.attr('number'),
  unittype: DS.attr('string'),
  variable: DS.attr('string'),
  variablename: DS.attr('string'),
  _order: DS.attr('number'),
});
