// Decennial Topics
import censusTopics from '../table-config/census';

export default [
  {
    id: 'populationDensity',
    label: 'Population Density',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.populationDensity,
    chartConfig: null,
    children: [],
  },
  {
    id: 'sexAndAge',
    label: 'Age and Sex',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.sexAndAge,
    chartConfig: null,
    children: [],
  },
  {
    id: 'mutuallyExclusiveRaceHispanicOrigin',
    label: 'Mutually Exclusive Race / Hispanic Origin',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.mutuallyExclusiveRaceHispanicOrigin,
    chartConfig: null,
    children: [],
  },
  {
    id: 'hispanicSubgroup',
    label: 'Hispanic Subgroup',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.hispanicSubgroup,
    chartConfig: null,
    children: [],
  },
  {
    id: 'asianSubgroup',
    label: 'Asian Subgroup',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.asianSubgroup,
    chartConfig: null,
    children: [],
  },
  {
    id: 'relationshipToHeadOfHouseholdHouseholder',
    label: 'Relationship to Head of Household',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.relationshipToHeadOfHouseholdHouseholder,
    chartConfig: null,
    children: [],
  },
  {
    id: 'householdType',
    label: 'Household Type',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.householdType,
    chartConfig: null,
    children: [],
  },
  {
    id: 'housingOccupancy',
    label: 'Housing Occupancy',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.housingOccupancy,
    chartConfig: null,
    children: [],
  },
  {
    id: 'housingTenure',
    label: 'Housing Tenure',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.housingTenure,
    chartConfig: null,
    children: [],
  },
  {
    id: 'tenureByAgeOfHouseholder',
    label: 'Tenure by Age of Householder',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.tenureByAgeOfHouseholder,
    chartConfig: null,
    children: [],
  },
  {
    id: 'householdSize',
    label: 'Household Size',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: censusTopics.householdSize,
    chartConfig: null,
    children: [],
  },
];
