// Decennial Topics
import decennialTopics from '../table-config/decennial';

export default [
  {
    id: 'populationDensity',
    label: 'Population Density',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.populationDensity,
    chartConfig: null,
    children: [],
  },
  {
    id: 'sexAndAge',
    label: 'Age and Sex',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.sexAndAge,
    chartConfig: null,
    children: [],
  },
  {
    id: 'mutuallyExclusiveRaceHispanicOrigin',
    label: 'Mutually Exclusive Race / Hispanic Origin',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.mutuallyExclusiveRaceHispanicOrigin,
    chartConfig: null,
    children: [],
  },
  {
    id: 'hispanicSubgroup',
    label: 'Hispanic Subgroup',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.hispanicSubgroup,
    chartConfig: null,
    children: [],
  },
  {
    id: 'asianSubgroup',
    label: 'Asian Subgroup',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.asianSubgroup,
    chartConfig: null,
    children: [],
  },
  {
    id: 'relationshipToHeadOfHouseholdHouseholder',
    label: 'Relationship to Head of Household',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.relationshipToHeadOfHouseholdHouseholder,
    chartConfig: null,
    children: [],
  },
  {
    id: 'householdType',
    label: 'Household Type',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.householdType,
    chartConfig: null,
    children: [],
  },
  {
    id: 'housingOccupancy',
    label: 'Housing Occupancy',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.housingOccupancy,
    chartConfig: null,
    children: [],
  },
  {
    id: 'housingTenure',
    label: 'Housing Tenure',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.housingTenure,
    chartConfig: null,
    children: [],
  },
  {
    id: 'tenureByAgeOfHouseholder',
    label: 'Tenure by Age of Householder',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.tenureByAgeOfHouseholder,
    chartConfig: null,
    children: [],
  },
  {
    id: 'householdSize',
    label: 'Household Size',
    selected: 'unselected',
    type: 'subtopic',
    tableConfig: decennialTopics.householdSize,
    chartConfig: null,
    children: [],
  },
];
